### ISSUE TITLE
Question regarding weighted Graph

### ISSUE THREAD

**Issue by lasys** [shsack/TQA-init.-for-QAOA#1]
Hello, 

thank you very much for the interesting paper. 
I'm currently writing my thesis about QAOA and i want to test your implementation against weighted graphs. 
I consider to change this lines to get it work, but i did not get any good results.. 
```
def H_C():
    tmp = np.zeros(2**N)
    for i, j, weight in edges:
        tmp += H[:, i] * H[:, j] * weight
    return tmp
```

It would be great, if you could help me! 
Thanks a lot!

**Comment by shsack** [comment]
Hi!

Great to see that the work is being read :) Good luck with your thesis, here are the two functions that I used for the weighted graph:

```
def weights(N, seed):

    np.random.seed(seed)
    a = np.random.rand(N, N)
    return np.tril(a) + np.tril(a, -1).T
```

```
def H_C_weighted():

    tmp = np.zeros(2**N)
    for i, j in edges:
        tmp += weights[i, j] * H[:, i] * H[:, j]
    return tmp
```

Best,
Stefan

**Comment by lasys** [comment]
Great! Thank you very much!
