### ISSUE TITLE
classical optimization based methods for QAOA setup?

### ISSUE THREAD

**Issue by LucidaLu** [shsack/TQA-init.-for-QAOA#2]
Thanks for your nice intuition and research results. This is indeed a neat and general method that can be widely used. But as a freshman studying QAOA, I am a little confused that what's the point of **classical optimization based** methods for QAOA setup.

~~Obviously, such methods cannot be utilized when NISQ devices are available since the optimization process would require exponential classical resources, so why should we study such methods which is not capable of solving large instances while the solution to small cases can be obtained by excessive search? In my view, such methods can only facilitate researching QAOA on small cases by saving time and computational resources. Do you agree? Please correct me if I am wrong.😊~~

Sorry for bothering you. I came to realize that the evaluation process was carried out on quantum computer.

**Comment by shsack** [comment]
Hi LucidaLu! 

In this work we analyzed the performance of the QAOA launched from a random initialization vs. the TQA initialization for small graph instances. As you correctly pointed out, we numerically studied this by classically computing the wave function which requires exponential computational resources (hence why we only considered small graphs). The QAOA is however straight forward to implement on a real quantum computer (which has been done successfully by a number of groups around the world), just not yet for the circuit depths considered in this work. I'm confident that in the near future we will see the first implementations of the TQA initialization for the QAOA on a real quantum computer (which obviously would no longer need exponential resources). 

Best,
Stefan

**Comment by LucidaLu** [comment]
Thanks for the reply! Having overly analyzed QAOA classically, I almost forgot what we expect from QAOA in the future. I will reach out if I have further results or questions~
